import type { Client } from './clients.types';

export const clientsMockData: Client[] = [
	{
		id: 'cli-001',
		name: 'ABC Corporation',
		code: 'CLI-0001',
		industry: 'Technology',
		status: 'active',
		activeProjects: 12,
		totalRevenue: 14.5,
		accountManager: 'Rahul Sharma',
		primaryContact: 'David Miller',
		email: 'contact@abccorp.com',
		location: 'Mumbai, India',
		description: 'Global provider of enterprise software and technology solutions.',
		joinedDate: '2022-03-15',
	},
	{
		id: 'cli-002',
		name: 'XYZ Limited',
		code: 'CLI-0002',
		industry: 'Financial',
		status: 'active',
		activeProjects: 7,
		totalRevenue: 9.8,
		accountManager: 'Priya Mehta',
		primaryContact: 'Sarah Jenkins',
		email: 'info@xyzlimited.com',
		location: 'London, UK',
		description: 'Multinational banking and financial services institution.',
		joinedDate: '2021-08-20',
	},
	{
		id: 'cli-003',
		name: 'Acme Industries',
		code: 'CLI-0003',
		industry: 'Healthcare',
		status: 'at-risk',
		activeProjects: 4,
		totalRevenue: 6.2,
		accountManager: 'Arjun Das',
		primaryContact: 'Robert Vance',
		email: 'partners@acmeind.com',
		location: 'New York, USA',
		description: 'Pharmaceutical research and healthcare systems manufacturer.',
		joinedDate: '2023-01-10',
	},
	{
		id: 'cli-004',
		name: 'Global Enterprises',
		code: 'CLI-0004',
		industry: 'Consulting',
		status: 'active',
		activeProjects: 9,
		totalRevenue: 11.4,
		accountManager: 'Sneha Kapoor',
		primaryContact: 'Elena Rostova',
		email: 'operations@globalent.com',
		location: 'Singapore',
		description: 'Strategic management consulting and business growth agency.',
		joinedDate: '2020-11-05',
	},
	{
		id: 'cli-005',
		name: 'TechNova',
		code: 'CLI-0005',
		industry: 'Technology',
		status: 'active',
		activeProjects: 6,
		totalRevenue: 7.9,
		accountManager: 'Vikram Singh',
		primaryContact: 'Amit Patel',
		email: 'tech@technova.io',
		location: 'Bengaluru, India',
		description: 'Next-gen cloud transformation and artificial intelligence startup.',
		joinedDate: '2023-06-18',
	},
	{
		id: 'cli-006',
		name: 'Nexus Retail',
		code: 'CLI-0006',
		industry: 'Retail',
		status: 'inactive',
		activeProjects: 0,
		totalRevenue: 3.1,
		accountManager: 'Rahul Sharma',
		primaryContact: 'Karen White',
		email: 'support@nexusretail.com',
		location: 'Toronto, Canada',
		description: 'Omnichannel retail supply chain and e-commerce platform.',
		joinedDate: '2019-04-12',
	},
	{
		id: 'cli-007',
		name: 'Vanguard Health',
		code: 'CLI-0007',
		industry: 'Healthcare',
		status: 'active',
		activeProjects: 5,
		totalRevenue: 8.3,
		accountManager: 'Priya Mehta',
		primaryContact: 'Dr. Marcus Vance',
		email: 'contact@vanguardhealth.org',
		location: 'Chicago, USA',
		description: 'Integrated healthcare network and telemedicine platform.',
		joinedDate: '2022-09-01',
	},
	{
		id: 'cli-008',
		name: 'Apex Capital',
		code: 'CLI-0008',
		industry: 'Financial',
		status: 'active',
		activeProjects: 8,
		totalRevenue: 12.1,
		accountManager: 'Arjun Das',
		primaryContact: 'Jonathan Sterling',
		email: 'invest@apexcapital.com',
		location: 'Frankfurt, Germany',
		description: 'Asset management and private equity investment firm.',
		joinedDate: '2021-02-14',
	},
	{
		id: 'cli-009',
		name: 'Omni Media Group',
		code: 'CLI-0009',
		industry: 'Consulting',
		status: 'at-risk',
		activeProjects: 3,
		totalRevenue: 4.6,
		accountManager: 'Sneha Kapoor',
		primaryContact: 'Rachel Green',
		email: 'hello@omnimedia.com',
		location: 'Sydney, Australia',
		description: 'Digital media strategy and brand communications agency.',
		joinedDate: '2023-10-22',
	},
	{
		id: 'cli-010',
		name: 'Zenith Logistics',
		code: 'CLI-0010',
		industry: 'Retail',
		status: 'active',
		activeProjects: 4,
		totalRevenue: 5.7,
		accountManager: 'Vikram Singh',
		primaryContact: 'Carlos Mendez',
		email: 'logistics@zenith.com',
		location: 'Madrid, Spain',
		description: 'Freight forwarding and automated warehouse systems.',
		joinedDate: '2022-07-30',
	},
];