import type { Resource } from './resources.types';

const STORAGE_KEY = 'ey_platform_resources_mock_v1';

const initialRoster: Resource[] = [
	{
		id: 'res-001',
		name: 'Aarav Nair',
		email: 'aarav.nair@company.com',
		role: 'Senior Architect',
		department: 'Technology',
		location: 'Bengaluru, India',
		allocationPercentage: 82,
		availabilityStatus: 'partially-allocated',
		assignedProjects: ['Atlas CRM', 'Digital Legacy'],
		billableRate: 135,
		skills: ['System Design', 'Java', 'Microservices'],
		experience: 12,
	},
	{
		id: 'res-002',
		name: 'Meera Joshi',
		email: 'meera.joshi@company.com',
		role: 'Project Manager',
		department: 'Consulting',
		location: 'Mumbai, India',
		allocationPercentage: 68,
		availabilityStatus: 'available',
		assignedProjects: ['Northstar Transformation'],
		billableRate: 110,
		skills: ['Stakeholder Management', 'Agile', 'Reporting'],
		experience: 9,
	},
	{
		id: 'res-003',
		name: 'Rohan Iyer',
		email: 'rohan.iyer@company.com',
		role: 'Full Stack Engineer',
		department: 'Technology',
		location: 'Pune, India',
		allocationPercentage: 96,
		availabilityStatus: 'fully-allocated',
		assignedProjects: ['Ops Portal', 'Customer Insights'],
		billableRate: 120,
		skills: ['React', 'Node.js', 'TypeScript'],
		experience: 8,
	},
	{
		id: 'res-004',
		name: 'Nisha Patel',
		email: 'nisha.patel@company.com',
		role: 'Data Scientist',
		department: 'Data',
		location: 'Hyderabad, India',
		allocationPercentage: 108,
		availabilityStatus: 'over-allocated',
		assignedProjects: ['Forecast Engine', 'Pricing Model'],
		billableRate: 128,
		skills: ['Python', 'Forecasting', 'SQL'],
		experience: 10,
	},
	{
		id: 'res-005',
		name: 'Vikram Sethi',
		email: 'vikram.sethi@company.com',
		role: 'UX Designer',
		department: 'Design',
		location: 'Delhi, India',
		allocationPercentage: 54,
		availabilityStatus: 'available',
		assignedProjects: ['Member Experience'],
		billableRate: 95,
		skills: ['Figma', 'Research', 'UX Strategy'],
		experience: 7,
	},
	{
		id: 'res-006',
		name: 'Sonia Khanna',
		email: 'sonia.khanna@company.com',
		role: 'Project Manager',
		department: 'Operations',
		location: 'Chennai, India',
		allocationPercentage: 77,
		availabilityStatus: 'partially-allocated',
		assignedProjects: ['Delivery Handoff', 'Program Governance'],
		billableRate: 112,
		skills: ['Risk Control', 'Scrum', 'Delivery'],
		experience: 11,
	},
	{
		id: 'res-007',
		name: 'Karan Malhotra',
		email: 'karan.malhotra@company.com',
		role: 'Full Stack Engineer',
		department: 'Technology',
		location: 'Austin, USA',
		allocationPercentage: 84,
		availabilityStatus: 'partially-allocated',
		assignedProjects: ['Partner Portal', 'Billing Core'],
		billableRate: 118,
		skills: ['React', 'C#', 'Azure'],
		experience: 9,
	},
	{
		id: 'res-008',
		name: 'Elena Brooks',
		email: 'elena.brooks@company.com',
		role: 'Senior Architect',
		department: 'Consulting',
		location: 'London, UK',
		allocationPercentage: 90,
		availabilityStatus: 'fully-allocated',
		assignedProjects: ['Cloud Strategy', 'Enterprise Architecture'],
		billableRate: 145,
		skills: ['Architecture', 'Cloud', 'EA'],
		experience: 14,
	},
	{
		id: 'res-009',
		name: 'Jai Menon',
		email: 'jai.menon@company.com',
		role: 'Data Scientist',
		department: 'Data',
		location: 'Singapore',
		allocationPercentage: 73,
		availabilityStatus: 'available',
		assignedProjects: ['Demand Analytics'],
		billableRate: 125,
		skills: ['Machine Learning', 'PyTorch', 'Visualization'],
		experience: 8,
	},
	{
		id: 'res-010',
		name: 'Priya Nair',
		email: 'priya.nair@company.com',
		role: 'UX Designer',
		department: 'Design',
		location: 'Bengaluru, India',
		allocationPercentage: 88,
		availabilityStatus: 'fully-allocated',
		assignedProjects: ['Customer Journey', 'Mobile App'],
		billableRate: 92,
		skills: ['Design Systems', 'Wireframes', 'Usability'],
		experience: 7,
	},
	{
		id: 'res-011',
		name: 'Dev Patel',
		email: 'dev.patel@company.com',
		role: 'DevOps Lead',
		department: 'Technology',
		location: 'Ahmedabad, India',
		allocationPercentage: 120,
		availabilityStatus: 'over-allocated',
		assignedProjects: ['Platform Enablement', 'CI/CD Modernization'],
		billableRate: 130,
		skills: ['Kubernetes', 'Terraform', 'GitHub Actions'],
		experience: 12,
	},
	{
		id: 'res-012',
		name: 'Leah Martin',
		email: 'leah.martin@company.com',
		role: 'Project Manager',
		department: 'Consulting',
		location: 'Toronto, Canada',
		allocationPercentage: 59,
		availabilityStatus: 'available',
		assignedProjects: ['Client Success Program'],
		billableRate: 116,
		skills: ['Portfolio Planning', 'Communication', 'Scope Control'],
		experience: 10,
	},
	{
		id: 'res-013',
		name: 'Omar Hassan',
		email: 'omar.hassan@company.com',
		role: 'Full Stack Engineer',
		department: 'Technology',
		location: 'Dubai, UAE',
		allocationPercentage: 102,
		availabilityStatus: 'over-allocated',
		assignedProjects: ['Portal Migration', 'Mobile Backend'],
		billableRate: 117,
		skills: ['React', 'GraphQL', 'Node.js'],
		experience: 9,
	},
	{
		id: 'res-014',
		name: 'Rhea Sen',
		email: 'rhea.sen@company.com',
		role: 'Data Scientist',
		department: 'Data',
		location: 'Kolkata, India',
		allocationPercentage: 61,
		availabilityStatus: 'available',
		assignedProjects: ['Retention Analysis'],
		billableRate: 124,
		skills: ['A/B Testing', 'Statistics', 'Power BI'],
		experience: 8,
	},
	{
		id: 'res-015',
		name: 'Tara Wilson',
		email: 'tara.wilson@company.com',
		role: 'UX Designer',
		department: 'Design',
		location: 'San Francisco, USA',
		allocationPercentage: 74,
		availabilityStatus: 'partially-allocated',
		assignedProjects: ['Service Design', 'Brand Refresh'],
		billableRate: 98,
		skills: ['UX Research', 'Prototype', 'Figma'],
		experience: 6,
	},
	{
		id: 'res-016',
		name: 'Anand Chawla',
		email: 'anand.chawla@company.com',
		role: 'Senior Architect',
		department: 'Operations',
		location: 'Gurugram, India',
		allocationPercentage: 72,
		availabilityStatus: 'available',
		assignedProjects: ['Infra Review'],
		billableRate: 138,
		skills: ['Solution Design', 'Governance', 'Cloud'],
		experience: 13,
	},
	{
		id: 'res-017',
		name: 'Sana Kulkarni',
		email: 'sana.kulkarni@company.com',
		role: 'Project Manager',
		department: 'Operations',
		location: 'Nagpur, India',
		allocationPercentage: 91,
		availabilityStatus: 'fully-allocated',
		assignedProjects: ['Program Delivery', 'Risk Review'],
		billableRate: 115,
		skills: ['Execution', 'Planning', 'Leadership'],
		experience: 10,
	},
	{
		id: 'res-018',
		name: 'Harish Rao',
		email: 'harish.rao@company.com',
		role: 'Full Stack Engineer',
		department: 'Technology',
		location: 'Bengaluru, India',
		allocationPercentage: 66,
		availabilityStatus: 'available',
		assignedProjects: ['Data Console'],
		billableRate: 121,
		skills: ['Vue', 'Node.js', 'Testing'],
		experience: 8,
	},
	{
		id: 'res-019',
		name: 'Maya Roberts',
		email: 'maya.roberts@company.com',
		role: 'Data Scientist',
		department: 'Consulting',
		location: 'Chicago, USA',
		allocationPercentage: 86,
		availabilityStatus: 'fully-allocated',
		assignedProjects: ['Client Insights', 'Dashboarding'],
		billableRate: 127,
		skills: ['Analytics', 'Python', 'Storytelling'],
		experience: 9,
	},
	{
		id: 'res-020',
		name: 'Daniel Park',
		email: 'daniel.park@company.com',
		role: 'DevOps Lead',
		department: 'Technology',
		location: 'Seoul, South Korea',
		allocationPercentage: 79,
		availabilityStatus: 'partially-allocated',
		assignedProjects: ['Release Pipeline', 'Monitoring'],
		billableRate: 133,
		skills: ['CI/CD', 'Observability', 'AWS'],
		experience: 11,
	},
];

function loadResources(): Resource[] {
	try {
		if (typeof window !== 'undefined' && window.localStorage) {
			const stored = localStorage.getItem(STORAGE_KEY);
			if (stored) {
				const parsed = JSON.parse(stored);
				if (Array.isArray(parsed) && parsed.length > 0) {
					return parsed;
				}
			}
		}
	} catch {
		// Ignore storage error
	}
	return initialRoster;
}

export const resourcesMockData: Resource[] = loadResources();

export function persistResources(data: Resource[]) {
	try {
		if (typeof window !== 'undefined' && window.localStorage) {
			localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
		}
	} catch {
		// Ignore storage error
	}
}
